name: tgma-hackathon
services:
  ui:
    container_name: tgma-hackathon-ui
    depends_on:
      - api
    build:
      context: ./ui
      dockerfile: docker/Dockerfile
    ports:
      - 8080:80
    restart: always
    volumes:
      - ui-node-modules-data:/app/node_modules

  api:
    container_name: tgma-hackathon-api
    env_file: .env.api
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - api-node-modules-data:/app/node_modules

volumes:
  api-node-modules-data:
  ui-node-modules-data:
